### PR TITLE
Used pip in script

### PR DESCRIPTION
**Pull request by PrimozGodec**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR introduces some changes to the recipe:

- pip is used for installation
- sha number is moved in package
- host requirements are introduced
- skip replaced with limiting python version

### CODE REVIEW

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by PrimozGodec** [comment]
@xylar if I remember correctly you suggested me to replace `skip: True  # [py2k]` with `python >=3.6` in another pull request. This is what I am trying to do in this PR but there seems to be an issue with Windows tests - the name of the directory is not correct because of the > sign. I googled the issue and couldn't find a good solution for that issue. Mostly it was suggested to introduce `skip` back. Do you know any better solution?

**Comment by xylar** [comment]
Could you try adding noarch: python and then rerendering again? This was the motivation for the switch. With noarch: python, you should only get the linux CI building a package for all py and all systems. Please do make sure your package is noarch, though. (Google if you need details.)

**Comment by PrimozGodec** [comment]
@xylar the reason why it is not `noarch: python` yet is that there is the `not windows` tag at of the requirements. If I am correct this line does not allow me to make the package noarch?

https://github.com/conda-forge/orange3-text-feedstock/blob/6f60f2f92dd3fc3600b2da11efde89ad98ad7c0b/recipe/meta.yaml#L48

This cannot be avoided yet since it is a fix for one of the bugs at the dependency. We are working on solving the issue.

**Comment by xylar** [comment]
Ah, got it.  In that case you are right, you can't do `noarch: python`.  And if that's the case, there's no advantage in going from `skip: True # [py2k]` to `python >=3.6`.  I had the impression that the python version, not the OS, was the reason for not going `noarch`.  I that case, stick with what you have.

**Comment by PrimozGodec** [comment]
@xylar thank you for your help. :) I will wait with this PR until we get rid of google-compute-engine.

**Comment by PrimozGodec** [comment]
I am closing this via #27, which is making this package no-arch

**Pull request closed without merging**
