### PR TITLE
Adding me as a maintainer

### PR DESCRIPTION
**Pull request by PrimozGodec**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@PrimozGodec, I was hoping one of the conda-forge core team would answer your request for help but given that hasn't happened, I'll jump in.

The problem here has nothing to do with this feedstock directly.  Instead, one of the dependencies is not yet built with python 3.7.  To find out which, I put the dependencies in a text file:
```
python=3.7
biopython
scipy
nltk>=3.0.5
scikit-learn
numpy
gensim>=0.12.3
setuptools-git
orange3>=3.4.3
anyqt
beautifulsoup4
validate_email
tweepy
simhash
wikipedia
typing
pdfminer3k>=1.3.1
odfpy>=1.3.5
docx2txt>=0.6
lxml
ufal.udpipe
ufal.udpipe-temp
py>=1.4.34
```
and tried to make an environment with that:
```
$ conda create --name test --file reqs.txt 
Collecting package metadata: done
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - python==3.7
  - wikipedia -> python=3.6 -> openssl[version='>=1.1.1a,<1.1.2a']
Use "conda search <package> --info" to see the dependencies for each package.
```
So it looks like the culprit (or perhaps one of a few culprits) is `wikipedia`.  Taking a look at that feedstock:
https://github.com/conda-forge/wikipedia-feedstock
it looks like an attempt was made to build it as a `noarch` package (so independent of python version or architecture) but that failed on merge for some reason:
https://github.com/conda-forge/wikipedia-feedstock/commits/master

I'll issue a pull request to attempt to get that fixed.

In the meantime, I would reset this PR back to your very first commit and then ask the bot to rerender once the `wikipedia` issue has been fixed.  The rest of your changes here are likely to have made things worse rather than better, I'm afraid.

**Comment by ajdapretnar** [comment]
@xylar Thank you so much for looking into this! @PrimozGodec We can perhaps disable Wikipedia widget for Py3.7 for the time being? That is in case the `noarch` version doesn't get through soon.

**Comment by xylar** [comment]
@ajdapretnar, there's also a note here:
https://github.com/conda-forge/wikipedia-feedstock/issues/4
suggesting that wikipedia might not be the preferred API.  Something to look into.

Getting the noarch build of `wikipedia` going shouldn't take long, though.

**Comment by xylar** [comment]
@ajdapretnar and @PrimozGodec, I'm working my way through the dependencies.  The next that is out of date is `validate_email`.  That feedstock also probably needs some attention.

**Comment by xylar** [comment]
The issue with `validate_email` is the same as with `wikipedia`: CI failed during the merging of a PR that had been successful:
https://github.com/conda-forge/validate_email-feedstock/commits/master

All the other dependencies are fine.  I'll do a PR to fix `validate_email` and you should be good after those go in.

**Comment by PrimozGodec** [comment]
@xylar Thank you for taking look at this PR. We will try to get rid of those two packages in the next release.

**Comment by xylar** [comment]
Okay, that's fine. But shouldn't be necessary.  They should be working in a few hours to a day, I would expect.

Note that you're several releases behind on building the feedstock so there's going to be some catching up to do.

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
`wikipedia-feedstock` is fixed but `validate_emails` not yet, so the new build will likely still fail.  That's why I was suggesting you not rerender until the other feedstocks are updated.  To get CI to run again once they are, you will now need to do a trivial commit. I'll let you know when it's time.

**Comment by xylar** [comment]
Here's the PR to watch for `validate_emails`:
https://github.com/conda-forge/validate_email-feedstock/pull/3

**Comment by xylar** [comment]
@PrimozGodec, both previously broken dependencies are now on the conda-forge channel as `noarch` so you should now (or soon will be) able to build with them.  I would hard-reset your local checkout of this branch to the commit with the changes the bot added and then test with a local python 3.7 build :
```
conda build --python=3.7 meta.yaml
```
If/when that is successful, in your local checkout of this branch, run
```
git commit --amend --no-edit && git push --force
```
This will trigger the CI to run again without making any changes to this feedstock.

**Comment by xylar** [comment]
I'm a little worried about the CI failing for python 3.6 under Linux.  That seems to be an unrelated issue to do with trying to use Qt on the CI.  I'm no expert but I know from `matplotlib` that you need to switch to a non-x-windows backend to get CI to work because it doesn't have a proper display.  The issue may be similar here and your import test may not be appropriate for CI without a display.  Let's see what happens...

**Comment by PrimozGodec** [comment]
The issue with libGL can be fixed by adding yum_requirements.txt with `mesa-libGL` inside. That is what we did for Orange3. https://github.com/conda-forge/orange3-feedstock/blob/master/recipe/yum_requirements.txt

**Comment by xylar** [comment]
@PrimozGodec, okay, glad you have a fix.  In that case, you should add back in your commit to include that.  Sorry for making you start over on this PR but I thought it was best to make sure.

There are a few other things one could play with, as you were.  But I would wait until this build is working before worrying about them (i.e. try them later in a separate PR):
* install with `pip` (a change I know you had already tried here)
* convert this to `noarch`: I don't see any reason not to.  You'd just need `python >=3.6` as a host and run requirement.

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Oops, I think you just undid the bot re-render.  That's why I was saying you need to fetch and then hard-reset.

**Comment by xylar** [comment]
I guess that was on purpose.

**Comment by PrimozGodec** [comment]
@xylar It is OK that I moved back to the beginning since there were too many unnecessary changes too. :) I will also change it to pip and noarch in one of the following PRs.

**Comment by xylar** [comment]
Sounds great!  I'll leave you alone because I think you're on your way.  If you run into trouble, let me know.

**Comment by PrimozGodec** [comment]
@xylar Realy thank you for your help. :) Now I learned how to act in cases with conflicts.

**Comment by PrimozGodec** [comment]
@conda-forge-admin, please rerender

**Comment by PrimozGodec** [comment]
@ajdapretnar @nikicc @astaric @kernc can someone merge that PR?

**Comment by ajdapretnar** [comment]
@xylar You are a star! 🌟 Thank you for your help!

**Comment by nikicc** [comment]
@ajdapretnar just beat me for a second 😏

**Comment by ajdapretnar** [comment]
💪 🏃‍♀ 😉

**Comment by xylar** [comment]
No problem.  Glad it worked out.

**Pull request merged**
